name: 'Setup'
description: 'Common setup for workflows.'
inputs:
  tf-version:
    description: 'Tensorflow version'
    required: false
    default: 'skip'  # Use sentinel value to skip Tensorflow installation
runs:
  using: 'composite'
  steps:
    - name: Get current date
      run: |
        echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_STATE
      shell: bash

    # Default pip caching doesn't work. See similar problem:
    # https://stackoverflow.com/questions/74119692/github-actions-setup-python-not-caching-pip-dependencies
    - uses: actions/setup-python@v4
      with:
        python-version: 3.7

    # The cache is refreshed everyday to pull updated dependencies.
    - uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ env.today }}-${{ inputs.tf-version }}

    # Install deps.
    - run: sudo apt install -y protobuf-compiler  # for gcld3 tests
      shell: bash
    - uses: FedericoCarboni/setup-ffmpeg@v2  # for Audio FeatureConnector tests.
    - if: ${{ inputs.tf-version != 'skip' }}
      run: pip install ${{ inputs.tf-version }}
      shell: bash
    - run: pip install -e .[tests-all]
      shell: bash
