name: Publish tensorflow-datasets to PyPI

# Allow to trigger the workflow manually (e.g. when deps changes)
on: [push, workflow_dispatch]

jobs:
  publish-job:
    # Prevents action from running on forks and non-master branches.
    if: |
      github.repository == 'tensorflow/datasets'
      && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Remove the `-nightly` suffix.
      # For stable version, we overwrite `version.py` by `version_stable.py` to
      # remove the `-nightly` suffix.
      run: mv tensorflow_datasets/version_stable.py tensorflow_datasets/version.py

    # Publish the package (if local `__version__` > pip version)
    - name: Publish the package
      uses: etils-actions/pypi-auto-publish@v1
      with:
        pypi-token: ${{ secrets.PYPI_API_TOKEN }}
        gh-token: ${{ secrets.GITHUB_TOKEN }}
        parse-changelog: true
